[package]
name = "selune-core"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
indexmap.workspace = true

[dev-dependencies]
proptest.workspace = true
criterion.workspace = true

[[bench]]
name = "value_bench"
harness = false
