[package]
name = "selune"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
selune-core.workspace = true
selune-compiler.workspace = true
selune-vm.workspace = true
selune-jit.workspace = true
selune-stdlib.workspace = true
rustyline = "14"
