[package]
name = "selune-vm"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
selune-core.workspace = true
selune-compiler.workspace = true
selune-stdlib.workspace = true

[dev-dependencies]
tempfile = "3"
